<?php
declare(strict_types=1);
require_once __DIR__.'/../../middleware/cors.php';
require_once __DIR__.'/../../middleware/auth.php';
$u=require_auth_user(); $db=db();
function inv_no(int $id): string { return 'INV-'.str_pad((string)$id,5,'0',STR_PAD_LEFT); }
if($_SERVER['REQUEST_METHOD']==='GET'){ $st=$db->prepare("SELECT i.id,i.invoice_number,i.issue_date,i.due_date,i.subtotal,i.tax_rate,i.tax_amount,i.total,i.status,i.created_at,c.name customer_name FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.user_id=? ORDER BY i.id DESC");$st->bind_param('i',$u['id']);$st->execute();$r=$st->get_result()->fetch_all(MYSQLI_ASSOC);foreach($r as &$x){$x['display_status']=($x['status']==='unpaid'&&$x['due_date']<date('Y-m-d'))?'overdue':$x['status'];}api_success(['invoices'=>$r]);}
if($_SERVER['REQUEST_METHOD']==='POST'){ $i=request_json(); $cid=(int)($i['customer_id']??0); $issue=(string)($i['issue_date']??date('Y-m-d')); $due=(string)($i['due_date']??date('Y-m-d',strtotime('+14 days'))); $tax=max(0,(float)($i['tax_rate']??0)); $notes=trim((string)($i['notes']??'')); $items=$i['items']??[]; if($cid<=0||!is_array($items)||!$items)api_error('customer_id and items are required.',422);
$ck=$db->prepare("SELECT id FROM customers WHERE id=? AND user_id=?");$ck->bind_param('ii',$cid,$u['id']);$ck->execute();if(!$ck->get_result()->fetch_assoc())api_error('Customer not found.',404);
$norm=[];$sub=0.0;foreach($items as $it){$d=trim((string)($it['description']??''));$q=(float)($it['quantity']??0);$p=(float)($it['unit_price']??0);if($d===''||$q<=0||$p<0)api_error('Invalid invoice item.',422);$line=round($q*$p,2);$sub+=$line;$norm[]=[$d,$q,$p,$line];}
$sub=round($sub,2);$taxAmt=round($sub*($tax/100),2);$total=round($sub+$taxAmt,2);$token=bin2hex(random_bytes(20));$db->begin_transaction();
try{$tmp='TEMP-'.bin2hex(random_bytes(4));$st=$db->prepare("INSERT INTO invoices(user_id,customer_id,invoice_number,issue_date,due_date,subtotal,tax_rate,tax_amount,total,status,notes,public_token) VALUES(?,?,?,?,?,?,?,?,?,'unpaid',?,?)");$st->bind_param('iisssddddss',$u['id'],$cid,$tmp,$issue,$due,$sub,$tax,$taxAmt,$total,$notes,$token);$st->execute();$id=(int)$db->insert_id;$num=inv_no($id);$up=$db->prepare("UPDATE invoices SET invoice_number=? WHERE id=?");$up->bind_param('si',$num,$id);$up->execute();$is=$db->prepare("INSERT INTO invoice_items(invoice_id,description,quantity,unit_price,line_total) VALUES(?,?,?,?,?)");foreach($norm as $row){$is->bind_param('isddd',$id,$row[0],$row[1],$row[2],$row[3]);$is->execute();}$db->commit();api_success(['invoice'=>['id'=>$id,'invoice_number'=>$num,'subtotal'=>$sub,'tax_amount'=>$taxAmt,'total'=>$total,'status'=>'unpaid','public_token'=>$token,'issue_date'=>$issue,'due_date'=>$due]],'Invoice created.',201);}catch(Throwable $e){$db->rollback();api_error('Could not create invoice.',500);}}
api_error('Method not allowed.',405);
